import { Header } from '@/components/common/Header/Header'
import './globals.css'
import { Inter , Montserrat} from 'next/font/google'
import { Footer } from '@/components/common/Footer/Footer'
import { Providers } from "@/store/provider";

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Providers>
        <Header />
        {children}
        <Footer />
        </Providers>
        
        </body>
    </html>
  )
}
